language: ruby
cache: bundler
bundler_args: --without production
rvm:
  - 2.5.0
before_install:
  - gem install bundler
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
  - "sh -e /etc/init.d/xvfb start"
script:
  bundle exec rspec spec
notifications:
  email: false